server:
  port: 18002

spring:
  datasource:
    username: root
    password: lmk951010
    url: jdbc:mysql://localhost:3306/mk?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
