server:
  port: 18002

spring:
  datasource:
    username: root
    password: lmk951010
    url: jdbc:mysql://localhost:3306/mk?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 2
      max-wait: 10000
  application:
    name: mk-baseservice

